[pytest]
#usefixtures = database
junit_logging: all
junit_log_passing_tests: True
junit_suite_name: ClinicalMdrApiTest
junit_family: xunit2
asyncio_mode = auto
asyncio_default_fixture_loop_scope="function"
log_cli=true
log_level=INFO
# This is needed to make the order to run within each module (each test)
addopts = --order-group-scope=module
filterwarnings =
    ignore:fields may not start with an underscore, ignoring:RuntimeWarning
    ignore:invalid escape sequence:DeprecationWarning
    ignore:The input looks more like a filename than markup:bs4.MarkupResemblesLocatorWarning
