@REQ_ID:1741028
Feature: Get released or locked study definition data from OpenStudyBuilder API

    Background: Test user must be able to call the OpenStudyBuilder API and test data exist
        Given The test user can call the OpenStudyBuilder API
        Given a test study identified by 'uid' is in status 'Locked' for the 'study_value_version'

    Rule: As an API user; I want the API to return an error code if a POST, PATCH or DELETE call is made on a locked study; So that I am not able to modify a locked study via the API.

        Scenario Outline: API must return error code and not make any data modifications if a POST, PATCH or DELETE /studies/<uid>/ endpoint is called with reference to a locked study
            When POST, PATCH or DELETE API endpoint '/studies/<uid>/<api-endpoint-area>' is called
            Then API must return error code '400' with message 'Study with specified uid <uid> is locked.'

            Examples:
                | TestID                                                        | api-endpoint-area         |
                | @TestID:test_activity_modify_actions_on_locked_study          | study-activities          |
                | @TestID:test_arm_modify_actions_on_locked_study               | study-arms                |
                | @TestID:test_branch_arm_modify_actions_on_locked_study        | study-branch-arms         |
                | @TestID:test_cohort_modify_actions_on_locked_study            | study-cohorts             |
                | @TestID:test_compound_modify_actions_on_locked_study          | study-compounds           |
                | @TestID:test_design_cell_modify_actions_on_locked_study       | study-design-cells        |
                | @TestID:test_disease_milestone_modify_actions_on_locked_study | study-disease-milestones  |
                | @TestID:test_standard_version_modify_actions_on_locked_study  | study-standard_versions   |
                | @TestID:test_endpoint_modify_actions_on_locked_study          | study-endpoints           |
                | @TestID:test_epoch_modify_actions_on_locked_study             | study-epochs              |
                | @TestID:modify_actions_on_locked_study                        | study-objects             |
                | @TestID:test_visit_modify_actions_on_locked_study             | study-visits              |


    Rule: As an API user; I want the API to return the locked or released study definition data; So that I can integrate to the data content as it was defined when the data was released or locked independent of the latest draft version.

        Scenario Outline: User must be able to call GET endpoints with reference to a locked study and get locked study content from when the study previously has been locked independent of later changes
            Given study values for attributes <attributes> has initial locked 'values'
            When test study is unlocked into Draft
            And PATCH API endpoint '/studies/<uid>/<api-endpoint-area>' is called
            And study values for attributes <attributes> is successfully updated to new values
            And GET API endpoint '/studies/<uid>/<api-endpoint-area>' is called with reference to the locked 'study_value_version'
            Then the API returns the call with a successful response code '200'
            And the returned <attributes> 'values' from the locked 'study_value_version' is identical to the initial <attributes> 'values'

            Examples:
                | TestID                                                             | api-endpoint-area        | attributes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
                | @TestID:test_study_activity_with_study_soa_group_relationship      | study-activities         | ["show_activity_in_protocol_flowchart","show_activity_subgroup_in_protocol_flowchart","show_activity_group_in_protocol_flowchart","show_soa_group_in_protocol_flowchart","study_activity_subgroup","study_activity_group","study_soa_group","activity","latest_activity"]                                                                                                                                                                                                                                                                                                             |
                | @TestID:test_study_arm_previous_study_version                      | study-arms               | ["name","short_name","code","description","arm_colour","randomization_group","number_of_subjects","arm_type","arm_connected_branch_arms"]                                                                                                                                                                                                                                                                                                                                                                                                                                             |
                | @TestID:test_study_branch_arm_study_versions                       | study-branch-arms        | ["name","short_name","code","description","colour_code","randomization_group","number_of_subjects","arm_root"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
                | @TestID:test_study_cohort_study_value_version                      | study-cohorts            | ["name","short_name","code","description","arm_colour","randomization_group","number_of_subjects","branch_arm_roots","arm_roots"]                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
                | @TestID:test_get_compound_doings_data_for_specific_study_version   | study-compound-dosings   | ["study_compound","study_element","dose_value","dose_frequency"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
                | @TestID:test_get_compounds_data_for_specific_study_version         | study-compounds          | ["compound","compound_alias","type_of_treatment","route_of_administration","strength_value","dosage_form","dispensed_in","device","formulation","other_info","reason_for_missing_null_value","study_compound_dosing_count"]                                                                                                                                                                                                                                                                                                                                                           |
                | @TestID:test_study_criteria_with_key_criteria                      | study-criteria           | ["criteria_type","criteria","criteria_template","key_criteria","latest_criteria","latest_template"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
                | @TestID:test_study_design_cell_with_study_epoch_relationship       | study-design-cells       | ["study_arm_name","study_branch_arm_name","study_element_name","transition_rule","order"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
                | @TestID:test_get_compound_data_for_specific_study_version          | study-disease-milestones | ["disease_milestone_type_named","disease_milestone_type_definition","disease_milestone_type","repetition_indicator","order"]                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
                | @TestID:test_get_compound_data_for_specific_study_version          | study-standard-versions  | ["disease_milestone_type_named","disease_milestone_type_definition","disease_milestone_type","repetition_indicator","order"]   
                | @TestID:test_study_element_with_study_element_subtype_relationship | study-elements           | ["name: ","short_name","code","description","planned_duration","start_rule","end_rule","element_colour","element_subtype","element_type","study_compound_dosing_count"]                                                                                                                                                                                                                                                                                                                                                                                                               |
                | @TestID:test_study_endpoint_with_study_objective_relationship      | study-endpoints          | ["study_objective","endpoint_level","endpoint_sublevel","endpoint_units","endpoint","timeframe","latest_endpoint","latest_timeframe","endpoint_template"]                                                                                                                                                                                                                                                                                                                                                                                                                             |
                | @TestID:test_study_epoch_with_study_epoch_subtype_relationship     | study-epochs             | ["start_rule","end_rule","epoch","epoch_subtype","duration_unit","order","description","duration","color_hash","epoch_name","epoch_subtype_name","epoch_type","epoch_type_name","start_day","end_day","start_week","end_week","study_visit_count"]                                                                                                                                                                                                                                                                                                                                    |
                | @TestID:test_study_objective_with_objective_level_relationship     | study-objectives         | ["objective_level","objective","objective_template","endpoint_count","latest_objective","accepted_version"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
                | @TestID:test_modify_actions_on_locked_study                        | study-soa-footnotes      | ["order","modified","referenced_items","footnote","footnote_template"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
                | @TestID:test_study_visit_versioning                                | study-visits             | ["study_epoch_name","order","visit_type_name","time_reference_uid","time_reference_name","time_value","time_unit_name","visit_contact_mode_name","epoch_allocation_name","duration_time","duration_time_unit","study_day_number","study_duration_days_label","study_day_label","study_week_number","study_duration_weeks_label","study_week_label","visit_number","visit_subnumber","unique_visit_number","visit_subname","visit_name","visit_short_name","visit_window_unit_name","visit_class","visit_subclass","is_global_anchor_visit"]                                           |




