repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: local
    hooks:
    - id: check-openapi-changes
      name: check-openapi-changes
      entry: ./.git-hooks/check-openapi-changes.sh
      language: system
      require_serial: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: pipenv
        language: system
        types: [python]
        pass_filenames: false
        args:
          [
            "run",
            "mypy",
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pipenv
        language: system
        types: [python]
        require_serial: true
        args:
          [
            "run",
            "pylint",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
default_language_version:
  python: python3.14
