services:

  # OpenStudyBuilder API service for running tests in pipeline
  api:
    extends:
      file: compose.yaml
      service: api
    build:
      args:
        TARGET: ${BUILD_TARGET:-dev}
        UID: ${UID:-1000}
    environment:
      NEO4J_DSN: "${NEO4J_DSN:-bolt://neo4j:changeme1234@database:7687/mdrdb}"
      UVICORN_ROOT_PATH: ""
      UVICORN_RELOAD: "true"
      EXPIRED_ACCESS_TOKEN: "${EXPIRED_ACCESS_TOKEN:-}"
      TRACE_REQUEST_BODY: "on"
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${API_PORT:-8000}:8000"
      - "127.0.0.1:5678:5678"
    volumes:
      - type: bind
        source: ./
        target: /app

  consumer-api:
    extends:
      file: compose.yaml
      service: consumer-api
    build:
      args:
        TARGET: ${BUILD_TARGET:-dev}
        UID: ${UID:-1000}
    environment:
      NEO4J_DSN: "${NEO4J_DSN:-bolt://neo4j:changeme1234@database:7687/mdrdb}"
      UVICORN_ROOT_PATH: ""
      UVICORN_RELOAD: "true"
    ports:
      - "127.0.0.1:5679:5678"
    volumes:
      - type: bind
        source: ./
        target: /app

  extensions-api:
    extends:
      file: compose.yaml
      service: extensions-api
    build:
      args:
        TARGET: ${BUILD_TARGET:-dev}
        UID: ${UID:-1000}
    environment:
      NEO4J_DSN: "${NEO4J_DSN:-bolt://neo4j:changeme1234@database:7687/mdrdb}"
      UVICORN_ROOT_PATH: ""
      UVICORN_RELOAD: "true"
    ports:
      - "127.0.0.1:5679:5678"
    volumes:
      - type: bind
        source: ./
        target: /app

  database:
    extends:
      file: compose.yaml
      service: database
    profiles:
      - database

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "127.0.0.1:9411:9411"
      - "::1:9411:9411"
    profiles:
      - zipkin

networks:
  default:
    driver: external
    name: studybuilder_dev-env
    external: true
