#########################################################################################
####  Export all user data from a StudyBuilder env and publish as pipeline artefact  ####
#########################################################################################

schedules:
- cron: "0 3 * * *"
  displayName: Daily build
  branches: 
   include:
   - main
  always: true 

trigger:
- none

# Global variables

pool:
  name: 'clinical-mdr-dev-vmss'

# Runtime parameters
parameters:
- name: DEPLOY_ID_NUMBER
  displayName: ID number of parallel deployments running in the same environment.
  type: string 
  default: '1'
  values:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
- name: ENV_REFERENCE
  displayName: Enviroment to export data from.
  type: string 
  default: 'PRD'
  values:
  - 'DEV'
  - 'TST'
  - 'EDU'
  - 'PRD'
- name: VAULT_NAME_PREFIX
  type: string
  default: kv-general

stages:
- stage: export_study_list
  jobs:
  - job: 'export_study_list'
    displayName: Export list of studies
    timeoutInMinutes: 10
    steps:
    - checkout: self
      persistCredentials: true
      submodules: true
      clean: true

    - task: AzureCLI@2
      displayName: Get AZ metadata
      name: azmd
      inputs:
        azureSubscription: IaCAgent-ClinicalMDR-${{parameters.ENV_REFERENCE}}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          namesuffix=`az network application-gateway list -g rg-ClinicalMDR-WEU-Application-${{parameters.DEPLOY_ID_NUMBER}}-${{parameters.ENV_REFERENCE}} -o tsv --query '[].[name]' | cut -d "-" -f 2`
          echo "##vso[task.setvariable variable=namesuffix;isOutput=true;]$namesuffix"
    # Get secrets from AzureKeyVault
    - task: AzureKeyVault@1
      displayName: Get oauth token
      inputs:
        azureSubscription: IaCAgent-ClinicalMDR-${{parameters.ENV_REFERENCE}}
        KeyVaultName: '${{parameters.VAULT_NAME_PREFIX}}-$(azmd.namesuffix)'
        RunAsPreJob: false  
        SecretsFilter:
          CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-STUDYB-SERVER-ID,
          CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-TOKEN-URL,
          CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-URI,
          CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-CODE-FLOW-SECRET,
          CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-STUDYB-ENABLE
    # Trust NN Certificate infrastructure
    - script: |
        sudo apt-get install ca-certificates
        sudo cp $(Build.SourcesDirectory)/certificatefiles/*.crt /usr/local/share/ca-certificates/
        sudo update-ca-certificates
      displayName: "Run Novo certificate operations"
    
    # Set Python Version
    - task: UsePythonVersion@0
      displayName: Python Version
      inputs:
        versionSpec: '3.14'
        addToPath: true
        architecture: 'x64'

    - script: |
        cd $(Build.SourcesDirectory)
        python3 -m venv venv --clear
        source $(Build.SourcesDirectory)/venv/bin/activate
        python -m pip install --upgrade pipenv
        python -m pip install wheel
        python -m pipenv lock
        python -m pipenv requirements > requirements.txt
        python -m pipenv install --dev
      displayName: "Install requirements"

    # Start export NOTE: REQUESTS_CA_BUNDLE is used for python to used OS CA certificate store.
    # WAF API export API_BASE_URL="https://studybuilder.clinicalmdr-${{lower(parameters.ENV_REFERENCE)}}.corp.azure.novonordisk.com/api"
    # Use CA Certs export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    # Direct API export API_BASE_URL="https://app-api-$(azmd.namesuffix).azurewebsites.net"
    - script: |
        source $(Build.SourcesDirectory)/venv/bin/activate

        [[ $(CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-STUDYB-ENABLE) == 1 ]] && export CLIENT_ID="$(CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-STUDYB-SERVER-ID)"
        export CLIENT_SECRET="$(CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-CODE-FLOW-SECRET)"
        export TOKEN_ENDPOINT="$(CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-TOKEN-URL)"
        export SCOPE="$(CLINICAL-MDR-AUTH-${{parameters.DEPLOY_ID_NUMBER}}-OAUTH-URI)/.default"

        export API_BASE_URL="https://app-api-$(azmd.namesuffix).azurewebsites.net"
        pipenv run export-study-list

      displayName: "Run export"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/output
        artifactName: studies.csv


