parameters:
- name: 'NEO4J_MDR_DATABASE'
  displayName: Name of neo4j DB
  type: string
  default: mdrdbdev
- name: 'NEO4J_CDISC_IMPORT_DATABASE'
  displayName: Name of intermediate DB
  type: string
  default: cdisc
- name: 'NEO4J_CDISC_IMPORT_BOLT_PORT'
  displayName: Bolt port of intermediate DB
  type: string
  default: 7687
- name: 'NEO4J_CDISC_IMPORT_HOST'
  displayName: IP address of intermediate DB
  type: string
  default: 10.78.43.90
- name: 'CDISC_DATA_DIR'
  displayName: Directory of CDISC JSON files
  type: string
  default: $(Build.SourcesDirectory)/json_data/packages
- name: REPO_REFERENCE
  type: string
  default: self  
- name: 'POOL'
  type: string
  default: false
- name: ID_NUMBER
  displayName: ID number of parallel deployments running in the same environment.
  type: string 
  default: '1'
  values:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
- name: ENV_REFERENCE
  type: string 
  default: DEV
  values:
  - DEV
  - POC
  - EDU
  - VAL
  - TST
  - PRD
- name: 'KEYVAULT_NAME'
  type: string
  default: false

jobs:
- job: ct_import
  pool: ${{parameters.POOL}}
  timeoutInMinutes: 720
  steps:  
    - checkout: ${{parameters.REPO_REFERENCE}}
    # Specify python version. The version must be manually installed beforehand so the agent has it available.
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.14'
        addToPath: true
        architecture: 'x64'

    # Get storage connection specifications from AzureKeyVault
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'clinicalmdr-iac-poc'
        KeyVaultName: '${{parameters.KEYVAULT_NAME}}'
        SecretsFilter: 
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBUSER,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBPASS,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-BOLTPORT,
          CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-SERVER
        RunAsPreJob: false

    # Install packages
    - script: |
        python3 -m venv venv --clear
        source $(Build.SourcesDirectory)/venv/bin/activate
        pip install pipenv
        python -m pipenv install
      displayName: Install packages and prepare
    # Load CT and adjust
    - script: |
        source $(Build.SourcesDirectory)/venv/bin/activate
        export NEO4J_MDR_DATABASE=${{parameters.NEO4J_MDR_DATABASE}}
        export NEO4J_MDR_BOLT_PORT=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-BOLTPORT)
        export NEO4J_MDR_HOST=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-SERVER)
        export NEO4J_MDR_AUTH_USER=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBUSER)
        export NEO4J_MDR_AUTH_PASSWORD=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBPASS)
        export CDISC_DATA_DIR=${{parameters.CDISC_DATA_DIR}}
        export NEO4J_CDISC_IMPORT_DATABASE=${{parameters.NEO4J_CDISC_IMPORT_DATABASE}}
        export NEO4J_CDISC_IMPORT_BOLT_PORT=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-BOLTPORT)
        export NEO4J_CDISC_IMPORT_HOST=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-SERVER)
        export NEO4J_CDISC_IMPORT_AUTH_USER=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBUSER)
        export NEO4J_CDISC_IMPORT_AUTH_PASSWORD=$(CLINICAL-MDR-NEO4J-${{parameters.ENV_REFERENCE}}${{parameters.ID_NUMBER}}-DBPASS)

        cp ${{parameters.CDISC_DATA_DIR}}/cdisc_data/packages/cdisc_ct/* ${{parameters.CDISC_DATA_DIR}}

        python -m pipenv run import_cdisc_ct_into_cdisc_db TESTUSER
      displayName: Download CT from CDISC API and import into CDISC DB
